### ISSUE TITLE
Hi, it's going to stay stuck here

### ISSUE THREAD

**Issue by eugle** [alexjackhughes/titan#1]
Hi, it's going to stay stuck here

![image](https://user-images.githubusercontent.com/24447931/78012364-6cb00980-7377-11ea-8f36-a7603150e374.png)

**Comment by kumarravigithub** [comment]
Yup! same with me.
It's stuck.
![Screenshot from 2020-04-04 23-41-01](https://user-images.githubusercontent.com/8915174/78458285-c5f89f80-76cd-11ea-8377-0a6719d57030.png)

**Comment by tomyo** [comment]
I would write the title of this issue differently, but yes, same here.

**Comment by alexjackhughes** [comment]
Hey guys, thanks for writing the issue!

I'm currently working through this to find a better way of clearing the cache in babel so that any graphQL you write is updated, in the mean time you can start the app just using the `meteor` command rather than `npm run dev` and it should work!

I'll update here as soon as I've pushed a patch - really appreciate you guys checking it out 👍

**Comment by alexjackhughes** [comment]
Just for my own reference going to add the investigative work that @techsavyravi did via Twitter: https://twitter.com/techsavyravi/status/1246501194454818816

**Comment by alexjackhughes** [comment]
Hey everyone! Thanks for holding in there, this bug should be fixed 🐛🥊 - I've pushed it straight to master so if you pull the latest commit you should be good to go!

Let me know if you have any other trouble!
